presupuesto/Controllers/CuentasController.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Diagnostics.HealthChecks;
using presupuesto.Models;
using presupuesto.Servicios;

namespace presupuesto.Controllers
{
    public class CuentasController : Controller
    {
        private readonly IRepositorioTiposCuentas repositorioTiposCuentas;
        private readonly IServicioUsuario servicioUsuario;
        private readonly IRepositorioCuentas repositorioCuentas;
        private readonly IMapper mapper;
		private readonly IRepositorioTransacciones repositorioTransacciones;
        private readonly IServicioReporte servicioReporte;

        public CuentasController(IRepositorioTiposCuentas repositorioTiposCuentas,IServicioUsuario servicioUsuario,IRepositorioCuentas repositorioCuentas,
            IMapper mapper, IRepositorioTransacciones repositorioTransacciones,IServicioReporte servicioReporte)
        {
            this.repositorioTiposCuentas = repositorioTiposCuentas;
            this.servicioUsuario = servicioUsuario;
            this.repositorioCuentas = repositorioCuentas;
            this.mapper = mapper;
			this.repositorioTransacciones = repositorioTransacciones;
            this.servicioReporte = servicioReporte;
        }

        // GET: CuentasController
        public async Task<IActionResult> Index()
        {
            var id_usuarios = servicioUsuario.ObtenerUsuarioServcio();
            var CuentasConTipoCuenta = await repositorioCuentas.Buscar(id_usuarios);

            var modelo = CuentasConTipoCuenta
                .GroupBy(x => x.TipoCuenta)
                .Select(grupo => new IndiceCuentasVM
                {
                    TipoCuenta = grupo.Key,
                    Cuenta = grupo.AsEnumerable()
                }).ToList();

            return View(modelo);
        }

        // GET: CuentasController/Details/5
   

        // GET: CuentasController/Create
        public async  Task<IActionResult> Crear()
        {
            var id_usuarios = servicioUsuario.ObtenerUsuarioServcio();
         
            var modelo = new CuentaCreacionVMD();

            modelo.TiposCuenta = await ObtenerTiposCuentas(id_usuarios);

            return View(modelo);
        }

        // POST: CuentasController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Crear(CuentaCreacionVMD cuenta)
        {
            var id_usuarios = servicioUsuario.ObtenerUsuarioServcio();
            var TiposCuenta = await repositorioTiposCuentas.ObtenerPorId(cuenta.id_TiposCuen,id_usuarios);

            if (TiposCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            if (!ModelState.IsValid)
            {
                cuenta.TiposCuenta =  await ObtenerTiposCuentas(id_usuarios);
                return View(cuenta);
            }

            await repositorioCuentas.Crear(cuenta);
            return RedirectToAction("Index");
        }

        private async Task<IEnumerable<SelectListItem>> ObtenerTiposCuentas(int id_usuarios)
        {
            var TiposCuentas = await repositorioTiposCuentas.Obtener(id_usuarios);
            return TiposCuentas.Select(x => new SelectListItem(x.Nombre, x.id_tiposCuen.ToString()));

        }


        // GET: CuentasController/Edit/5
        public async Task<IActionResult> Editar(int id)
        {
            var id_usuarios = servicioUsuario.ObtenerUsuarioServcio();
            var cuenta = await repositorioCuentas.ObtenerPorId(id, id_usuarios);

            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }
            //forma manual de mappear de una clase a otra
            //var modelo = new CuentaCreacionVMD()
            //{
            //    id_cuenta = cuenta.id_cuenta,
            //    Nombre = cuenta.Nombre,
            //    id_TiposCuen = cuenta.id_TiposCuen,
            //    Descripcion = cuenta.Descripcion,
            //    Balance = cuenta.Balance
            //};

            var modelo = mapper.Map<CuentaCreacionVMD>(cuenta);

            modelo.TiposCuenta = await ObtenerTiposCuentas(id_usuarios);

            return View(modelo);
        }
        // POST: CuentasController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(CuentaCreacionVMD cuentaEditar)
        {
            var id_usuarios = servicioUsuario.ObtenerUsuarioServcio();
            var cuenta = await repositorioCuentas.ObtenerPorId(cuentaEditar.id_cuenta, id_usuarios);

            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            var tipoCuenta = await repositorioTiposCuentas.ObtenerPorId(cuentaEditar.id_TiposCuen, id_usuarios);
            if (tipoCuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioCuentas.Actualizar(cuentaEditar);
            return RedirectToAction("Index");
        }

        // GET: CuentasController/Delete/5
        [HttpGet]
        public async  Task<IActionResult> Borrar(int id)
        {
            var id_usuarios = servicioUsuario.ObtenerUsuarioServcio();
            var cuenta = await repositorioCuentas.ObtenerPorId(id, id_usuarios);

            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }


            return View(cuenta);
        }

        // POST: CuentasController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BorrarCuenta(int id_cuenta)
        {
            var id_usuarios = servicioUsuario.ObtenerUsuarioServcio();
            var cuenta = await repositorioCuentas.ObtenerPorId(id_cuenta, id_usuarios);

            if (cuenta is null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await repositorioCuentas.Borrar(id_cuenta);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detalle(int id, int mes, int anio)
        {
			var id_usuarios = servicioUsuario.ObtenerUsuarioServcio();
            var cuenta = await repositorioCuentas.ObtenerPorId(id, id_usuarios);

			if (cuenta is null)
			{
				return RedirectToAction("NoEncontrado", "Home");
			}

            ViewBag.Cuenta = cuenta.Nombre;

            var modelo = await servicioReporte.ObtenerReporteTramsaccionesDetalladasPorCuenta(id_usuarios, id, mes, anio, ViewBag);

            return View(modelo);
        }
    }
}

presupuesto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - presupuesto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/presupuesto.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/lib/fullcalendar/main.min.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand"  asp-controller="Transaccion" asp-action="Index">presupuesto</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="TiposCuentas" asp-action="Index">Tipos Cuentas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cuentas" asp-action="Index">Cuenta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Categorias" asp-action="Index">Categorias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Transaccion" asp-action="Index">Transacciones</a>
                        </li>
                    </ul>
                    <partial name="_LinksLogin"></partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - presupuesto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

presupuesto/Views/Shared/_LinksLogin.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Usuario> SignInManager

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <span class="nav-link text-dark">Hola, @User.Identity.Name</span>
        </li>
        <li class="nav-item">
            <form class="form-inline" asp-action="logout" asp-controller="usuarios">
                <button type="submit" class="nav-link btn btn-link text-dark">
                    Logout
                </button>
            </form>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="usuarios" asp-action="Registro">Registro</a>
        </li>
        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="usuarios" asp-action="Login">Login</a>
        </li>
    }
</ul>

presupuesto/Views/Shared/_NavegarPorMeses.cshtml
@model DateTime


<h4>
    <a asp-route-mes="@ViewBag.mesAnterior" asp-route-anio="@ViewBag.anioAnterior" class="btn btn-secondary">
        <i class="bi-chevron-left"></i>
    </a>
    @Model.ToString("MMM")-@Model.Year
    <a asp-route-mes="@ViewBag.mesPosterior" asp-route-anio="@ViewBag.anioPosterior" class="btn btn-secondary">
        <i class="bi-chevron-right"></i>
    </a>
</h4>

presupuesto/Views/Shared/_ReporteTransacionesDetalladas.cshtml
@model ReporteTransccionesDetallas
@{
    var resumentMontos = new ResumenMontosMVD()
            {
                Ingresos = Model.BalanceDepositos,
                Gastos = Model.BalanceRetiros,
                Total = Model.Total
            };
}

<h4>
    <a asp-route-mes="@ViewBag.mesAnterior" asp-route-anio="@ViewBag.anioAnterior" class="btn btn-secondary">
        <i class="bi-chevron-left"></i>
    </a>
    @Model.FechaInicio.ToString("MMM")-@Model.FechaInicio.Year
    <a asp-route-mes="@ViewBag.mesPosterior" asp-route-anio="@ViewBag.anioPosterior" class="btn btn-secondary">
        <i class="bi-chevron-right"></i>
    </a>
</h4>

<partial name="_ResumenMontos" model="@resumentMontos"></partial>

@if(Model.TransaccionesAgrupadas.Count() == 0)
{
    <h5>No hay datos para mostrar</h5>
}
else{
  <table class="table">
        <tbody>
            @foreach (var transaccionAgrupada in Model.TransaccionesAgrupadas)
            {
                <tr style="background-color: lightblue; font-size:26px;">
                    <td colspan="3">
                        @transaccionAgrupada.FechaTransaccion.Day
                            <span class="badge bg-secondary">
                                @transaccionAgrupada.FechaTransaccion.ToString("ddd")
                            </span>
                    </td>
                    <td class="activo">@transaccionAgrupada.BalanceDepositos.ToString("N")</td>
                    <td class="pasivo">@transaccionAgrupada.BalanceRetiros.ToString("N")</td>
                </tr>
                @foreach (var transaccion in transaccionAgrupada.Transacciones)
                {
                    <tr style="vertical-align:middle">
                        <td>
                            <a asp-controller="transaccion" asp-action="Editar" asp-route-id="@transaccion.id_transacciones" asp-route-urlRetorno="@ViewBag.urlRetorno">
                                <i class="bi-pencil"></i>
                            </a>
                        </td>
                        <td>@transaccion.Categoria </td>
                        <td>@transaccion.Cuenta</td>
                        <td class="activo">@(transaccion.id_TiposOp == TipoOperacion.Ingreso ? transaccion.monto.ToString("N") : null) </td>
                        <td class="pasivo">@(transaccion.id_TiposOp == TipoOperacion.Gastos ? transaccion.monto.ToString("N") : null)</td>
                    </tr>
                   
                }
            }
        </tbody>
  </table>  

}

presupuesto/Views/Shared/_ResumenMontos.cshtml
@model ResumenMontosMVD


<div class="contenedor-totales">
    <div>
        <div>
            <strong>Depositos</strong>
        </div>
        <div class="activo">
            @Model.Ingresos.ToString("N")
        </div>
    </div>
    <div>
        <div>
            <strong>Retiros</strong>
        </div>
        <div class="pasivo">
            @Model.Gastos.ToString("N")
        </div>
    </div>
    <div>
        <div>
            <strong>Total</strong>
        </div>
        <div>
            @Model.Total.ToString("N")
        </div>
    </div>
</div>